### ISSUE TITLE
visudo check warnings for RACF ids

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/sudoport#5]
The user ids listed are RACF defined.

cd /hewitt/zopentools/guild/sudo*/sbin
./visudo -c -f /hewitt/zopentools/my_sudo/sudoers

/hewitt/zopentools/my_sudo/sudoers:72:14: Runas_Alias "T0UDPP" referenced but not defined
/hewitt/zopentools/my_sudo/sudoers:73:14: Runas_Alias "P0UDPP" referenced but not defined
/hewitt/zopentools/my_sudo/sudoers:76:14: Runas_Alias "T0EDMP" referenced but not defined
/hewitt/zopentools/my_sudo/sudoers:77:14: Runas_Alias "P0EDMP" referenced but not defined
/hewitt/zopentools/my_sudo/sudoers:80:14: Runas_Alias "BFJAVA" referenced but not defined
/hewitt/zopentools/my_sudo/sudoers: parsed OK

**Comment by IgorTodorovskiIBM** [comment]
Thanks, should have a fix for this shortly

**Comment by IgorTodorovskiIBM** [comment]
Will be fixed by https://github.com/ZOSOpenTools/sudoport/pull/7

**Comment by gngrossi** [comment]
bash-5.2$ cd /hewitt/zopentools/guild/sudo*/sbin
bash-5.2$ ./visudo -c -f /hewitt/zopentools/my_sudo/sudoers
/hewitt/zopentools/my_sudo/sudoers: parsed OK
